name: hi_kod_5proje
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  confetti: ^0.6.0

  # State Management
  get: ^4.6.6

  get_storage: ^2.1.1

  card_swiper: ^3.0.1

  lottie: ^3.3.1

  numberpicker: ^2.1.2

  animated_text_kit: ^4.2.3

  google_fonts: ^6.2.1

  # Utility Packages
  smooth_page_indicator: ^1.1.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/onboarding/
    - assets/images/
