name: hi_kod_5proje
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  confetti: ^0.6.0
  category_navigator: ^1.1.6

  # State Management
  get: ^4.6.6

  get_storage: ^2.1.1

  # Utility Packages
  smooth_page_indicator: ^1.1.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  carousel_slider: ^5.0.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding_images/
    - assets/images/card_images/
